### ISSUE TITLE
auth login: Does not launch the browser

### ISSUE THREAD

**Issue by ahmetb** [planetscale/cli#250]
I am using macOS 11.3.1 (20E241)

```
# pscale auth login
Press Enter to authenticate via your browser...
```

Stays there and does not launch a Chrome tab.

**Comment by fatih** [comment]
Hi @ahmetb Does it happen even if you hit enter? Which version do you use (`pscale version`)?

**Comment by ahmetb** [comment]
It worked when I hit enter.
/facepalm I actually did not read the message properly as most of these kinds of tools just launch the browser.

**Comment by fatih** [comment]
Haha, no worries :) I wonder though if we can make it simpler and improve the experience. 

@iheanyi what do you think about opening the browser immediately?

**Comment by iheanyi** [comment]
@fatih I'm open to doing that, might not be a bad idea to be honest.

**Comment by pys1992** [comment]
+1 same issue.
macos 11.3.1 (20E241)
pscale version 0.35.0 (build date: 2021-05-18T19:05:10Z commit: 313750b)
