### ISSUE TITLE
Un-delete-able lines in history

### ISSUE THREAD

**Issue by croaky** [planetscale/cli#251]
My apologies if this is another environmental issue on my side! But figured I'd document it either way.

When I press the "up" arrow key to go back through the CLI history, the first key press returns the previous command. The second key press:

* returns the first 19 characters of the previous command. Or, if the previous command is shorter than 19 characters, it returns the previous command and pads empty spaces through the 19th character.
* begins the second-previous command in the 20th column

When I try to delete the line, I can't delete those first 19 characters. If I type a new command and hit "enter", the new command works. So, I think it's just a strange visual thing.

https://user-images.githubusercontent.com/198/118705829-8d326180-b7cd-11eb-929a-2122837241f3.mov

I don't experience this in the general `mysql` CLI.

My `~/.pscale/history/croaky.example.main` file looks like this:

```
_HiStOrY_V2_
show\040tables;
describe\040users;
show\040tables;
exit
show\040tables;
describe\040users;
exit
describe\040reminders;
select\040*\040from\040reminders;
```

MySQL appears to be linked to libedit/editline:

```
% otool -L "$(which mysql)"
/opt/homebrew/opt/mysql-client/bin/mysql:
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

I have no overrides in `~/.editrc`.

**Comment by aquarapid** [comment]
@croaky, for the record, what version of the mysql CLI bin is that?

**Comment by croaky** [comment]
```
% brew info mysql-client
mysql-client: stable 8.0.23 (bottled) [keg-only]

% mysql --version
mysql  Ver 8.0.23 for osx10.16 on x86_64 (Homebrew)
```

Looks like 8.0.23

**Comment by fatih** [comment]
Hi @croaky 

Does this also happen if you call it with `--no-color` flag?

**Comment by croaky** [comment]
It does not happen with the `--no-color` flag!

**Comment by fatih** [comment]
It looks like it's due to the ANSI escape sequences we use for colorizing the `mysql` command-line tool's prompt. 

Honestly, I'm not sure exactly how we can solve this. We don't have control over the `mysql` Command line tool. We set all the important details and then run the tool. I'll share more information if I find anything that we can use to fix this issue. 

Meanwhile ,you can disable the colors via `--no-color` flag or the `NO_COLOR=true` environment variable.

**Comment by fatih** [comment]
We disabled prompt coloring for the MySQL CLI, so this issue shouldn't happen anymore. Please let us know if you see any issues.

**Comment by croaky** [comment]
Thanks @fatih!
