### ISSUE TITLE
Couldn't find the 'mysql' client

### ISSUE THREAD

**Issue by heymartinadams** [planetscale/cli#253]
Def have the mysql client installed with `brew install mysql-client`, but when I do `pscale shell testdb main` is gives me this error:

```
Error: couldn't find the 'mysql' client required to run this command.
To install, run: brew install mysql-client
```

Reinstalling `mysql-client` didn’t work either.

**Comment by iheanyi** [comment]
Thanks for reporting this. Could you run a `which mysql` and tell us what pops?

**Comment by heymartinadams** [comment]
Ah, thanks for that. Noob error: had to add it to the `$PATH`, then restart Terminal.

```
echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> ~/.zshrc
```
