### ISSUE TITLE
Shell: Unknown Option `--defaults-extra-file`

### ISSUE THREAD

**Issue by nickelkr** [planetscale/cli#275]
Trying to run `pscale shell <database> <branch>` I receive the error:
```bash
➜  ~ pscale shell thunks main                  
/usr/bin/mysql: unknown option --defaults-extra-file
Error: exit status 1
```
`pscale` version:
```bash
➜  ~ pscale --version
pscale version 0.39.0 (build date: 2021-05-24T12:03:51Z commit: b321aeb)
```

`mysql` version:
```bash
➜  ~ mysql --version
mysql   Ver 8.0.25 for Linux on x86_64 - for MySQL 8.0.25 (MySQL Community Server (GPL))
```

Running on:
```bash
➜  ~ uname -srm
Linux 5.11.14-1-MANJARO x86_64
```

It does work if I use `pscale connect` and then start the `mysql` shell from the command line and pass in the proper args.

**Comment by fatih** [comment]
Hi @nickelkr 

This looks interesting. Here is the official doc showing and explaining the flag: `--defaults-extra-file`

https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_defaults-extra-file

I have this option with this version on macOS:

```
$ mysql --version
mysql  Ver 8.0.23 for osx10.16 on x86_64 (Homebrew)
```

Could you run `man mysql` and search for this flag? Do you see any flags there starting with `--defaults...`?

**Comment by nickelkr** [comment]
I don't have a manual entry for it and installed it via the generic Linux tarball from https://dev.mysql.com/downloads/shell/

However the help does not display that as a option. This binary also unpacks as `mysqlsh`, if that makes a difference. Although it still shows a similar version/name when executed:
```bash
➜  ~ mysql --version
mysql   Ver 8.0.25 for Linux on x86_64 - for MySQL 8.0.25 (MySQL Community Server (GPL))```

**Comment by fatih** [comment]
> This binary also unpacks as mysqlsh

Do you rename this binary to `mysql` by any chance?

> I don't have a manual entry for it and installed it via the generic Linux tarball at https://dev.mysql.com/downloads/shell/

Ok, that's the issue. So `mysqlsh` is a completely different tool than the `mysql` command-line tool. I wished they wouldn't create two different CLI tools, but that's what it is.

Please remove your current installation and follow the instructions from here: https://dev.mysql.com/doc/refman/8.0/en/linux-installation.html

This will also provide you the `mysql` command-line tool, which has the `--defaults-extra-file` flag.

**Comment by nickelkr** [comment]
Thanks, that provided the expected binary.
