### ISSUE TITLE
How do we use the cli in Serverless function environment?

### ISSUE THREAD

**Issue by aniljaiswal** [planetscale/cli#282]
I want to try out the PlanetScale MySQL service in my AWS Lambda functions. How do I go about it?

**Comment by mscoutermarsh** [comment]
Hi @aniljaiswal - we're working on setting up an easy way to do this. Likely with a Lambda layer. Hope to have a solution ASAP.

**Comment by aniljaiswal** [comment]
@mscoutermarsh Thanks, Mike! Can't wait to try this out and take this into production.

**Comment by aniljaiswal** [comment]
I'll leave this open just in case we have more people interested to follow the thread.

**Comment by dbussink** [comment]
I'm going to close this one as we've shipped connection strings which allow for direct connections from any language! https://twitter.com/planetscaledata/status/1427371097352069120

**Comment by dbussink** [comment]
See also https://docs.planetscale.com/concepts/connection-strings for documentation on the new feature.
