### ISSUE TITLE
connect: bubble up exit code of `--execute` command when done

### ISSUE THREAD

**Issue by janpio** [planetscale/cli#283]
0.40.0 added the great feature that `connect` ends when the command in `--execute` ends. Unfortunately `pscale connect` still exits with status code 1, which a test runner or CI system of course interpret as a failure: https://github.com/prisma/e2e-tests/pull/1700/checks?check_run_id=2669053383#step:5:134

It would be great if the CLI could pick up the exit code of the wrapped command, and bubble that up and exit `pscale connect` with that.

**Comment by fatih** [comment]
Hi @janpio 

You're right; it shouldn't exit with `1`. I checked the logs above, though, and it looks like the proxy (`pscale connect`) left with no issues. In that case, we exit with the status `0`. Did you see any other logs that could indicate an error? I wonder if we somehow return an error in the case where we should log it.

I'm currently looking into wrapping the execute command's status code and will share a working branch with you.

**Comment by janpio** [comment]
> You're right; it shouldn't exit with `1`. I checked the logs above, though, and it looks like the proxy (`pscale connect`) left with no issues. In that case, we exit with the status `0`. Did you see any other logs that could indicate an error? I wonder if we somehow return an error in the case where we should log it.

I based this off `pscale connect e2e-tests main --execute-protocol 'mysql' --debug --execute 'yarn test'` being the last command being run, and then the process exiting with status code 1:
```
exitting with code 1
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
```

I can retry to get a manual reproduction.

**Comment by fatih** [comment]
@janpio This issue should be now fixed with the PR: https://github.com/planetscale/cli/pull/287

I released a new version with this improvement. If you update to `v0.42.0` (https://github.com/planetscale/cli/releases/tag/v0.42.0), you should be able to try it out. Please let me know if you see any issues.

**Comment by janpio** [comment]
Thanks!

Somehow it is not working for me/us:

```
run.sh was successful, running databases/planetscale/test.sh...

pscale version 0.42.0 (build date: 2021-06-01T14:28:46Z commit: 59880fe)

2021-06-01T14:48:17Z	info	adding tls.Config to the cache	{"instance": "***/e2e-tests/main"}
2021-06-01T14:48:17Z	info	ready for new connections
2021-06-01T14:48:17Z	info	listening remote DB instance	{"local_addr": "127.0.0.1:3306", "instance": "***/e2e-tests/main"}
Secure connection to database e2e-tests and branch main is established!.

Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
yarn run v1.22.10
warning ../../package.json: No license field
$ jest
2021-06-01T14:48:19Z	info	new connection	{"conn_addr": "127.0.0.1:3306"}
2021-06-01T14:48:19Z	info	using tls.Config from the cache	{"instance": "***/e2e-tests/main"}
2021-06-01T14:48:19Z	info	connecting to remote server	{"remote_addr": "main.e2e-tests.***.us-east-1.psdb.cloud:3307"}
PASS ./index.test.js
  tests for database
    ✓ should test the Prisma version (2 ms)
    ✓ should query the database (629 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        1.902 s
Ran all test suites.
Done in 2.54s.
2021-06-01T14:48:19Z	info	received context cancellation, waiting until timeout	{"timeout": "1s"}
2021-06-01T14:48:19Z	info	no connections to wait, bailing out
Error: skipping update, reason: Latest version (v0.42.0) is less than or equal to current build version (0.42.0)

finished test.sh

-----------------------------
databases/planetscale done
exitting with code 1
Warning: Attempt 1 failed. Reason: Child_process exited with error code 1
```

Can you quickly run your `demo 0` (from https://github.com/planetscale/cli/pull/287#issue-659050023) via `pscale connect` with `--debug` (as I do in the CI output) so I can compare the output?

**Comment by fatih** [comment]
> Error: skipping update, reason: Latest version (v0.42.0) is less than or equal to current build version (0.42.0)

I think it's due to this message. Here is the code in our CLI that returns the error:

```
	err = rootCmd.Execute()
	if err != nil {
		return err
	}

	if *format == printer.Human {
		err := update.CheckVersion(ver)
		if err != nil && debug {
			return err
		}
	}

	return nil
```

It looks like `rootCmd.Execute()` returns with zero exit status and proceeds to run the updater. And that returns an error. 

Could you run it without the `--debug` and see whether it works? That would disable returning the error from the update.

**Comment by janpio** [comment]
Ha, my hunch was kinda right. I thought setting the env var I found in the update checker code would help, but seems not: `Error: skipping update, reason: PSCALE_NO_UPDATE_NOTIFIER is set`

Let's see what happens without `--debug`.

**Comment by janpio** [comment]
Indeed, leaving out `--debug` fixes it:

```
...

run.sh was successful (code 0), running databases/planetscale/test.sh...

pscale version 0.42.0 (build date: 2021-06-01T14:28:46Z commit: 59880fe)

Secure connection to database e2e-tests and branch main is established!.

Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
yarn run v1.22.10
warning ../../package.json: No license field
$ jest
PASS ./index.test.js
  tests for database
    ✓ should test the Prisma version (2 ms)
    ✓ should query the database (362 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        1.671 s
Ran all test suites.
Done in 2.35s.

finished test.sh (code 0)

...
```

**Comment by fatih** [comment]
Thank you, @janpio, for the Feedback. I’ll make sure to fix it. Let’s keep this issue open until then.

**Comment by fatih** [comment]
@janpio I released a fix with the version 
https://github.com/planetscale/cli/releases/tag/v0.44.0

Please let me know if you see any issues.

**Comment by janpio** [comment]
That worked, I can now run tests with `--debug`:

```
run.sh was successful (code 0), running databases/planetscale/test.sh...

pscale version 0.45.0 (build date: 2021-06-03T14:27:51Z commit: 86df35e)

2021-06-03T19:23:24Z	info	adding tls.Config to the cache	{"instance": "***/e2e-tests/main"}
2021-06-03T19:23:24Z	info	ready for new connections
2021-06-03T19:23:24Z	info	listening remote DB instance	{"local_addr": "127.0.0.1:3306", "instance": "***/e2e-tests/main"}
Secure connection to database e2e-tests and branch main is established!.

Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
yarn run v1.22.10
warning ../../package.json: No license field
$ jest
2021-06-03T19:23:26Z	info	new connection	{"conn_addr": "127.0.0.1:3306"}
2021-06-03T19:23:26Z	info	using tls.Config from the cache	{"instance": "***/e2e-tests/main"}
2021-06-03T19:23:26Z	info	connecting to remote server	{"remote_addr": "main.e2e-tests.***.us-east-1.psdb.cloud:3307"}
PASS ./index.test.js
  tests for database
    ✓ should test the Prisma version (3 ms)
    ✓ should query the database (170 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   1 passed, 1 total
Time:        1.31 s
Ran all test suites.
Done in 1.90s.
2021-06-03T19:23:26Z	info	received context cancellation, waiting until timeout	{"timeout": "1s"}
2021-06-03T19:23:26Z	info	no connections to wait, bailing out

finished test.sh (code 0)
```

Thanks!
