### ISSUE TITLE
`execute` command does not accept `'`

### ISSUE THREAD

**Issue by keita-makino** [planetscale/cli#340]
I have tried the way to launch my server along with the `connect` command with an `--execute` option but have got the following error. Oddly, it also asks which database branch I would connect even though I've specified it in the command line.

As this from the example does not work basically I cannot run any commands. Is there something wrong with my approach?

```cmd
C:\Users\apricot\src\kemakino\3RFM-ITS-Davis\publication-manager\server>pscale connect publication next --execute 'node app.js'  
? Select a branch to connect to: next
Secure connection to database publication and branch next is established!.      

Local address to connect your application: 127.0.0.1:3306 (press ctrl-c to quit)
Error: failed to parse command, not running: invalid command line string
```

**Comment by keita-makino** [comment]
Found the cause. I couldn't use ' there and instead had to use ".

```
pscale connect publication next --execute 'node app.js' // NG
pscale connect publication next --execute "node app.js" // OK

"scripts": {
  "start": "pscale connect publication next --execute \"ts-node --transpile-only api/app.ts\"", // OK
}
```

Is this specific to my environment or a more general issue that we need to fix the docs?

**Comment by fatih** [comment]
Hi @keita-makino 

It shouldn't matter whether you use a `'` or `"`. It's the shell that you're using that interprets it. Here is an example of using both quote characters, you'll see that they have the same length and representation:

![ScreenShot-2021-07-15-at-10 20 20@2x](https://user-images.githubusercontent.com/438920/125746264-a57c06a2-8cc2-4961-bef8-35d9bbad45b1.png)

What shell are you using? What is your operating system? If you're using macOS can you try your command in the `Terminal.app` application? 

Another suggestion would be to switch to a different shell temporarily. As an example, if you're using `zsh`, type `bash` first, hit enter, and then run the `pscale` command.

**Comment by janpio** [comment]
On Windows (which @keita-makino is using, see their path) `'` is not a quote character, but a normal character. This problem Happens quite often for Windows terminals/shells/consoles/whatever is the correct name users when you follow Linux or macOS specific documentation, as there `'` works fine and is considered the standard :shrug:

**Comment by fatih** [comment]
>On Windows (which @keita-makino is using, see their path) ' is not a quote character, but a normal character so can not be used to quote strings (with e.g. spaces, which makes that necessary). 

I totally missed it, thanks for the tip Jan.

> This problem Happens quite often for Windows terminals/shells/consoles/whatever is the correct name users when you follow Linux or macOS specific documentation, as there ' works fine and is considered the standard 🤷

That's good to know. To be honest, our Windows users are low, but we still want to make it easy for them. I'll make sure any of our public docs are using `"` double quotes instead of single quotes.

**Comment by fatih** [comment]
I'll close this issue as we know what the main problem is. Please feel free to re-open the issue if you think it's not resolved.
