### ISSUE TITLE
Segmentation fault when trying to enter the shell of the main branch.

### ISSUE THREAD

**Issue by kasipavankumar** [planetscale/cli#376]
# Issue statement
Greetings.

I'm trying to get into the shell of the `main` branch and the command `pscale shell <database> main` started throwing 

```bash
Error: signal: segmentation fault (core dumped)
``` 

Although, the command seem to work fine with other branches.

For some context, **I'm using the CLI inside a newly spun container based on the Ubuntu 20:04 image**. Authentication and deploy request were the commands made prior to this error and those were successful.

# Screenshot
![image](https://user-images.githubusercontent.com/44864604/130422545-660f6ce5-835f-4479-b97b-09d142a2dafb.png)

# Version
`pscale version 0.68.0 (build date: 2021-08-19T11:23:27Z commit: 6c41383)`

**Comment by fatih** [comment]
Hi @kasipavankumar 

It looks like something with your container is wrong. Can you please run it with our official docker container and let us know if you see any issues? : 

```
$ docker pull planetscale/pscale:v0.68.0
$ docker run -it 
  --env PLANETSCALE_SERVICE_TOKEN= <token> 
  --env PLANETSCALE_SERVICE_TOKEN_NAME=<name>  
  --env PLANETSCALE_ORG=<org>   
  planetscale/pscale  shell links main
```

**Comment by kasipavankumar** [comment]
Hi. Sure let me

**Comment by kasipavankumar** [comment]
Hi.
Sure, let me try it.

**Comment by kasipavankumar** [comment]
Error cannot be reproduced anymore. 
Maybe, it was some container configuration issue.
Thanks.
