### ISSUE TITLE
What dependencies are exactly needed?

### ISSUE THREAD

**Issue by zeekrey** [planetscale/cli#384]
Hey there,

I tried to run `pscale shell <database> <branch>` but I keep getting:

`Error: couldn't find the 'mysql' command-line tool required to run this command.
To install, follow the instructions: https://dev.mysql.com/doc/refman/8.0/en/windows-installation.html`

I installed the Developer Default bundle. Running msqlsh --version returns:

`C:\Program Files\MySQL\MySQL Shell 8.0\bin\mysqlsh.exe   Ver 8.0.26 for Win64 on x86_64 - for MySQL 8.0.26 (MySQL Community Server (GPL))`

But I still get there error above. Would be awesome if somebody could explain which package is exactly needed on a windows machine.

**Comment by JuniorDEVed** [comment]
I had the same issue, it took me 16 hours to work around on windows. I had to install wsl2 and then try 3 different distros, eventually after setting up ubuntu, I installed msql command line tools and mysql client and eventually it worked.

Honestly I think this needs a rethink... it was painful to get this up and running. Also pre built binary for windows really doesn't fit nicely, why can't it be as simple as choco install pscale and were up and running!

**Comment by jgreet** [comment]
@zeekrey `pscale shell` is looking for the `mysql.exe` command-line client. If you installed MySQL Server you should be able to find it at `C:\Program Files\MySQL\MySQL Server 8.0\bin`. You'll want to add that directory to the PATH for whatever shell you're using.

https://docs.planetscale.com/reference/planetscale-environment-setup#windows-instructions

Sorry this isn't simpler on a Windows machine, I'll ask the team to take a look.

**Comment by zeekrey** [comment]
Seems that the _MySQL Developer Bundle_ only sets the path variable for the shell (mysqlsh). Adding mysql to the path solves the problem.

Changing the cli error message from:

`Error: couldn't find the 'mysql' command-line tool required to run this command. To install, follow the instructions: https://dev.mysql.com/doc/refman/8.0/en/windows-installation.html`

to:

`Error: couldn't find the 'mysql' command-line tool required to run this command. To install, follow the instructions: https://docs.planetscale.com/reference/planetscale-environment-setup#windows-instructions`

would have save me some minutes and increase the dev experience. 

Keep up the great work! 🚀

**Comment by fatih** [comment]
Thank you @zeekrey for the feedback. I opened PR that improves the error message and links to our official documentation: https://github.com/planetscale/cli/pull/385
