### ISSUE TITLE
How to use service tokens with the CLI headlessly?

### ISSUE THREAD

**Issue by fominv** [planetscale/cli#425]
Hi

I am trying to integrate the Planetscale CLI with Drone CI & CD. I have created a service token for my organization, but I just cannot get it to work. 

Could you give me a hint on how to use service tokens with the CLI as it is not documented in the docs.

Currently, I try to create a shell wrapper function and alias it to the pscale command such that I do not need to add the service token to any subsequent invocations. 

```bash
function pscale_wrapper () {
    sleep 4
    pscale "$@" \
        --org ${PSCALE_ORG} \
        --service-token ${PSCALE_SERVICE_TOKEN} \
        --service-token-name ${PSCALE_SERVICE_TOKEN_NAME}
}

alias pscale="pscale_wrapper"
```

This leads me to the following error in Drone:

```
Error: not authenticated yet. Please run 'pscale auth login' or create a service token with 'pscale service-token create'
```

Thank you in advance!

**Comment by fominv** [comment]
The issue was in my bash coding and not in the Planetscale CLI.

Shell aliases need to be sourced properly before they can be used. I changed the code as follows and everything works:

```bash
function pscale-auth () {
    sleep 4
    pscale "$@" \
        --org ${PSCALE_ORG} \
        --service-token ${PSCALE_SERVICE_TOKEN} \
        --service-token-name ${PSCALE_SERVICE_TOKEN_NAME}
```

Note that you then need to call the pscale-auth shell function directly. 

Additionally, I ran into problems as my service token was not able to create deploy requests, but this could resolved by granting access via the CLI. The necessary access is not visible in the web UI for some reason.

**Comment by fatih** [comment]
@fominv you can also set `PLANETSCALE_SERVICE_TOKEN` and `PLANETSCALE_SERVICE_TOKEN_NAME` environment variables, so you don't need to create the wrapper at all.

 > Additionally, I ran into problems as my service token was not able to create deploy requests, but this could resolved by granting access via the CLI. The necessary access is not visible in the web UI for some reason.

You can give access to tokens. What exactly did you try and it didn't work out for you?

**Comment by fominv** [comment]
@fatih Thanks! Using the variables is way more ergonomic :)

My issue was that if you create a service token via the web UI, then you do not see certain permissions like create_deploy_request, i.e. the web UI does not show all available permissions for service tokens.

This lead to my Drone pipeline failing, but I could resolve it by adding the necessary permissions via the Planetscale CLI.
