### ISSUE TITLE
Using within Github Action

### ISSUE THREAD

**Issue by danconger** [planetscale/cli#426]
Are there any examples of using this within a Github Action? Our team is looking at switching to Planetscale, but needs to accomplish the following with our preview urls in Vercel:
1. Not step on each other's toes in preview environment
2. Deterministically seed a few items into the database before our Next.js repo statically generates a few pages.

I can provide our current Github Action for accomplishing this with a Postgres db if that would be helpful.

**Comment by jonico** [comment]
@danconger: Here are some examples for GitHub Action based workflows: https://github.com/jonico/matrix-demos

**Comment by jonico** [comment]
@danconger: An improved way of doing this can be found in this repository: https://github.com/jonico/pscale-cli-helper-scripts
Example video: https://youtu.be/qAs-NNWvihQ
