### ISSUE TITLE
Linux client points to 404 page

### ISSUE THREAD

**Issue by CodingSpiderFox** [planetscale/cli#438]
Didn't have mysql commandline util installed

Error output was 

Error: couldn't find the 'mysql' command-line tool required to run this command.
To install, follow the instructions: https://docs.planetscale.com/reference/planetscale-environment-setup#linux-instructions

Link does not work

**Comment by CodingSpiderFox** [comment]
CLI version 0.87.0 downloaded and installed manually from GitHub

**Comment by mscoutermarsh** [comment]
@CodingSpiderFox Does that link work for you now? It's working for me. Does it 404?

**Comment by CodingSpiderFox** [comment]
works :)
