### ISSUE TITLE
CLI should wait for new branch to be ready

### ISSUE THREAD

**Issue by CodingSpiderFox** [planetscale/cli#439]
Steps taken:

Created account and database instance, connected to it, made "main" the production branch, created a branch with a table and 1 entry, promoted it.
Ran `pscale branch create <mydatabasename> <newbranchname>`
Ran pscale shell <mydatabasename> <newbranchname>`
Commandline output was 
`Error: database branch is not ready yet`

Instead I would have expected to have a message `please wait` and the command line client not return with exitcode != 0, instead, connect to the DB as soon as the branch creation completes

**Comment by pkoch** [comment]
Maybe a `--wait` flag, or something, wouldn't be a bad idea.

**Comment by iheanyi** [comment]
A `--wait` flag isn't a bad idea. Will look into this when we're back in the office

**Comment by CodingSpiderFox** [comment]
An additional flag is too much typing ... just make it the default behaviour or at least configurable system wide via config file

**Comment by pcgeek86** [comment]
> Maybe a `--wait` flag, or something, wouldn't be a bad idea.

Came here to say this.

**Comment by jgreet** [comment]
A `--wait` option for `pscale branch create` was added in https://github.com/planetscale/cli/pull/510 and is avilable in v0.98.0
