### ISSUE TITLE
Enable scripted login without browser verification

### ISSUE THREAD

**Issue by JasonEtco** [planetscale/cli#446]
Hello! I was attempting to setup the `pscale` CLI within a [GitHub Codespace](https://github.com/features/codespaces), and encountered a slight blocker. I can download and install the binary, but _true_ automation would mean also logging in with a Service/API token automatically. Unfortunately, that doesn't seem possible, given:

https://github.com/planetscale/cli/blob/f5f28252be30850151c7412046b0b4740cc55eb9/internal/cmd/auth/login.go#L32-L34

I would assume that by passing a `--service-token` to `pscale auth login`, it would use the token _without_ requiring an additional step. Could there be a flag to bypass that step? I have no idea how complicated that'd be from the other end.

### My setup

In any case, here's my whole setup:

**`.devcontainer.json`**

```json
{
  "onCreateCommand": "script/on-codespace-create"
}
```

**`script/on-codespace-create`**

```shell
#!/bin/sh

# Download PlanetScale CLI
curl -s https://api.github.com/repos/planetscale/cli/releases/latest \
  | grep browser_download_url \
  | grep "linux_amd64.deb" \
  | cut -d : -f 2,3 \
  | tr -d \" \
  | wget -qi - -P ~

# Install it
sudo dpkg -i ~/pscale_*_linux_amd64.deb
```

### Ideal solution

Ideally, I'd like to do this:

```shell
# ...
# Install it
sudo dpkg -i ~/pscale_*_linux_amd64.deb

# Login using the Service token environment variable
pscale auth login --service-token=$PSCALE_SERVICE_TOKEN
```

That way I could either immediately start using `pscale`, or even connect to a dev database automatically. Right now that prompts like this (which of course works fine, but can't be fully automated):

```
Failed to open a browser: exec: "xdg-open": executable file not found in $PATH

Confirmation Code: <REDACTED>

If something goes wrong, copy and paste this URL into your browser: https://auth.planetscale.com/oauth/device?user_code=<REDACTED>

⠧ Waiting for confirmation... 
```

<sub>Hi @mscoutermarsh 🥺 👉 👈 </sub>

**Comment by tbarn** [comment]
Hey @JasonEtco! 

With service tokens, you don't need to `auth login` at all, you can just pass them in. You are halfway there with `--service-token <string>`. You also need to use the `--service-token-name <string>` flag too. 

(Also, this flag is about to get a small change to make it more accurate too: https://github.com/planetscale/cli/pull/447, but it will still work with a deprecation notice.)

We also have some helper scripts located in https://github.com/jonico/pscale-cli-helper-scripts that might be useful too.

**Comment by JasonEtco** [comment]
Oh! Thanks for this, lots of helpful things in here 🙏 The documentation for `--service-token-name` isn't clear about what its used for so I didn't realize it was necessary.

[This line](https://github.com/jonico/pscale-cli-helper-scripts/blob/main/.pscale/cli-helper-scripts/use-pscale-docker-image.sh#L24), in particular `PSCALE_ALLOW_NONINTERACTIVE_SHELL` feels really useful, but isn't documented anywhere. I'll play around with these options!

**Comment by JasonEtco** [comment]
Finally had a chance to try this out! Running specific commands (like `pscale connect`) worked great:

```sh
pscale connect db_name main \
  --port 3309 \
  --service-token-name=$PSCALE_SERVICE_TOKEN_ID \
  --service-token=$PSCALE_SERVICE_TOKEN \
  --org=jasonetco # Fun fact, this is case-sensitive! Found out the hard way 😎
```

It would be awesome to `pscale auth login` to persist it, so that I can run `pscale *` easily without having to do another kind of auth - but this works great for my use-case 😊 

You're welcome to close this, or leave it open in case an automated/persisted `pscale auth login` sounds fun to you!
