### ISSUE TITLE
Setting `database` in `.my.cnf` breaks `pscale shell`

### ISSUE THREAD

**Issue by paulrosania** [planetscale/cli#453]
For convenience, I have a `~/.my.cnf` file configured to connect to my development MySQL instance -- this lets me run `mysql` with no arguments.

This seems to break `pscale shell`, which spits out this error:
```
ERROR 1105 (HY000): unknown database '<database name>'
Error: exit status 1
```

I suspect `pscale` isn't specifying the database to connect to when it invokes the MySQL CLI. Is that something you could fix? It would make the local workflow a lot nicer. Thanks for your consideration. :)

**Comment by Andre361** [comment]
I had the same issue.

**Comment by mscoutermarsh** [comment]
Fix will be included in the next release (soon!)

**Comment by paulrosania** [comment]
Incredible, thank you!
