### ISSUE TITLE
pscale cli database dumps are always in .sql format?

### ISSUE THREAD

**Issue by 933459** [planetscale/cli#467]
trying to dump a test Planetscale database into local files with pscale CLI. 

it appears that no matter what options i give to "pscale database dump ... " i get a directory full of .sql files. example:

"pscale database dump myDatabase myDatabaseBranch -output csv --format csv" --> a dir called "csv" full of .sql files.

"pscale database dump myDatabase myDatabaseBranch -output json --format json" --> a dir called "json" full of .sql files.

"pscale database dump myDatabase myDatabaseBranch -output human --format human" --> a dir called "human" full of .sql files.

am i missing something here? i hardly consider myself an expert, but this seems to not work as intended/as the cli help describes.

**Comment by jgreet** [comment]
I think the documentation might be a little confusing when it comes to this particular command.

`--format` is a global flag for formatting pscale's output:

```bash
$ pscale database show eu-test --format human
  NAME      CREATED AT   UPDATED AT   NOTES
 --------- ------------ ------------ -------
  eu-test   4 days ago   4 days ago

$ pscale database show eu-test --format json
{
  "name": "eu-test",
  "notes": "",
  "region": {
    "slug": "eu-west",
    "display_name": "EU West",
    "location": "Dublin",
    "enabled": true
  },
  "created_at": "2022-03-03T12:44:02.507Z",
  "updated_at": "2022-03-03T12:45:50.29Z"
}
```

`pscale database dump` will only create SQL files.
