### ISSUE TITLE
`pscale deploy-request close` failing with "Error: Actor must exist"

### ISSUE THREAD

**Issue by eddeee888** [planetscale/cli#495]
## Overview

I'm trying to use the CLI to close a deploy request. It seems to correctly close the deploy request but always returns non zero error with this message: `Error: Actor must exist`, regardless of using CLI or docker image.

Version 0.93.0

## Details

Here's how I use it:

```bash
$ PLANETSCALE_SERVICE_TOKEN=<token> \
  PLANETSCALE_SERVICE_TOKEN_NAME=<token_name> \
  pscale deploy-request close <database_name> <deploy_request_number> --org <org_name>
```

It'll show return this in the terminal:

```
Error: Actor must exist
```

Here's what it looks like in the UI, note how it says "Ghost" :

<img width="560" alt="Screen Shot 2022-04-25 at 6 06 11 pm" src="https://user-images.githubusercontent.com/33769523/165046805-bb84e645-4f9b-4726-98e6-4f644bd40316.png">

Merge events also say "Ghost" as the actor and don't throw this error. Not sure if this is intended.

## Expected result

`pscale deploy-request close` should not throw non zero errors if the deploy request is closed.

**Comment by drakedeatonuk** [comment]
I've also been encountering this error - does anyone have any advice on this?

**Comment by mscoutermarsh** [comment]
Thanks for reporting! We're getting this fixed.

**Comment by mscoutermarsh** [comment]
Fix for this is deploying now. When closing via a service token, it will now work + you'll see in the UI the token that closed it.
