### ISSUE TITLE
Timeout issues when running "pscale auth login"

### ISSUE THREAD

**Issue by ruskid** [planetscale/cli#511]
I am using this version:
pscale version 0.98.0 (build date: 2022-06-13T13:57:40Z)

```
➜  ~ pscale auth login --debug
Updater error: skipping update, error: Get "https://api.github.com/repos/planetscale/cli/releases/latest": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Error: Post "https://auth.planetscale.com/oauth/authorize_device": dial tcp: lookup auth.planetscale.com: i/o timeout
```

**Comment by dbussink** [comment]
@ruskid What platform are you on? It looks like this is a timeout from your DNS, so are you able to resolve `auth.planetscale.com` correctly on your machine and is the DNS server reachable? 

If you're on a Mac and using an IPv6 DNS server with a link local address, you might be hitting https://github.com/planetscale/discussion/discussions/181.

**Comment by ruskid** [comment]
yes, I can resolve both domains: auth.planetscale.com and api.planetscale.com. My DNS is reachable and I don't have any IPv6 domains defined in resolv.conf

I think the issue might be with PlanetScale blocking the country I am based in, Georgia. Authentication worked when I connected to Germany via VPN

**Comment by ruskid** [comment]
Resolved my compiling with Go. Thanks to this thread -  planetscale/discussion#181

**Comment by dbussink** [comment]
> Resolved my compiling with Go. Thanks to this thread - [planetscale/discussion#181](https://github.com/planetscale/discussion/discussions/181)

@ruskid Are you able to share the contents of `/etc/resolv.conf` in your case? And you're on MacOS or on another operating system?
