### ISSUE TITLE
[Feature Request] Add --wait flag for deploy-request deploy sub-command

### ISSUE THREAD

**Issue by orware** [planetscale/cli#518]
[PR#510](https://github.com/planetscale/cli/pull/510) solved several pending issue requests once the `--wait` ability for `pscale branch create` was added, but there is still a pending need to also have this available for `pscale deploy-request deploy`.

Based on @jonico's helper scripts in addition to the recently completed PR, there is definitely a need also for the same treatment in the `deploy` sub-command:
https://github.com/jonico/pscale-workflow-helper-scripts/blob/main/.pscale/cli-helper-scripts/wait-for-deploy-request-merged.sh

We've had more than one user making this request and it is directly something that would help their automation attempts using the CLI.

I initially thought this would be needed for `pscale deploy-request create` but creating a deploy request seems to be relatively fast/instant so it probably doesn't need a `--wait` option.

When using the `deploy` sub-command however, the action is queued with the following message:

```
Successfully queued <DEPLOY_REQUEST_NANOID> from <DEVELOPMENT_BRANCH> for deployment to <PRODUCTION_BRANCH>.
```

With a `--wait` flag available, the user would be able to use that and then know that deploy request has successfully deployed once the command returns, rather than needing to create a polling situation to check.

Further review of other asynchronous commands might also be necessary if needed to see if a similar `--wait` flag might be helpful, but if this one is addressed then it'll complete the top two we've received requests about in recent months.

**Comment by orware** [comment]
@fatih I'm not sure if this one might be easily able to be tackled due to the recent work in [PR#510](https://github.com/planetscale/cli/pull/510) but if it can be I have a user that would be most appreciative of its availability :D.

**Comment by erikrob** [comment]
I am coming back to see if this enhancement is still on anyone's radar ? 
We want to to do planet scale deployments as part our CI/CD scripts and the absence of --wait flags on certain commands (we'd need it on deploy-request create, deploy-request deploy, and deploy-request close) makes it impossible to script things synchronously. 
Are we the only customers who want to do deployments as part of automated flows ? If not I'm curious as to how others do it?
Thanks.
