### ISSUE TITLE
Error: "pscale org" cmd producing "Requires authentication" error with service-token & service-token-id present

### ISSUE THREAD

**Issue by drakedeatonuk** [planetscale/cli#534]
Currently, I'm unable to use PlanetScale's service tokens to authenticate any "pscale org" commands. 

In any "pscale org" CLI command, if I use the --service-token & --service-token-id flags, I get a "Requires authentication" error.

See the service token here:
![Screenshot 2022-07-10 at 11 48 43](https://user-images.githubusercontent.com/41165256/178141749-993f56da-121a-4d8a-b8e8-34f1be293d31.png)

And some examples of "pscale org" cli commands:
![Screenshot 2022-07-10 at 11 47 21](https://user-images.githubusercontent.com/41165256/178141807-cbd5d29e-9edd-47d6-ab43-5e1989805607.png)
![Screenshot 2022-07-10 at 12 01 58](https://user-images.githubusercontent.com/41165256/178142174-7c345d63-cb00-4f16-b352-8c0089ea5a38.png)

Maybe this is by design, but it was fairly ambiguous to me as to why that'd be the case, particularly as in the [org cli docs it specifies that you can use service token flags](https://docs.planetscale.com/reference/org).

**Comment by mscoutermarsh** [comment]
Thank you! We'll check on this.

I believe this is a mistake in our documentation/error messages. Service tokens are limited to accessing databases only.

**Comment by drakedeatonuk** [comment]
Good to know thanks for clearing that up :)
