### ISSUE TITLE
Web Hooks for Deploy Request status changes

### ISSUE THREAD

**Issue by mohsen1** [planetscale/cli#557]
I'm working on an automation system based on Github Actions. You can find my work in progress here:

https://github.com/mohsen1/planetscale-prisma-github-action

To make this project successful I need a Web Hook from PlanetScale to send me a signal when a Deploy Request is approved/rejected.  Is this something that you're offering or plan to support? I can pool for now but Web Hooks are nicer and more standard. 

<hr>
It would be nice if you could offer more than one database branch to free accounts so I can try this idea easier.

**Comment by mscoutermarsh** [comment]
Thanks for opening this @mohsen1. We don't have any plans at the moment to build webhooks. Best option for now is polling the [deploy requests API ](https://api-docs.planetscale.com/reference/get-a-deploy-request) endpoint.

**Comment by mscoutermarsh** [comment]
FYI - Webhooks have been released: https://planetscale.com/blog/introducing-webhooks
