### ISSUE TITLE
Installing planet scale cli on windows 7 64bit

### ISSUE THREAD

**Issue by mattjaf** [planetscale/cli#587]
I'm currently running powershell 2.0 with .NET 4.0 and i was trying to install it manually since the scoop installation command seems to require PS 3.0+

is this "pscale_0.124.0_windows_amd64.zip" the file I should be downloading for manually installation?

and if so do i just unzip it into program files and run the .exe from powershell?

**Comment by orware** [comment]
Hi @mattjaf,

That file would be the correct one for a Windows installation!

Another option to what you described would be to create a `C:\pscale` folder and then place the contents of the ZIP into that folder.

Afterwards you can add `C:\pscale` into your [Windows PATH](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/).

You should then be able to open up a `CMD` or PowerShell prompt and type `pscale version` to see the version you have installed. 

For future updates you can just grab the latest Windows ZIP and replace over the existing files in your `C:\pscale` folder.

**Comment by orware** [comment]
For Windows 7 the procedure to add a folder to the path is similar, just not as nice as on Windows 10 and newer but you should still be able to [add in the new path to the existing list separated by semicolons](https://www.computerhope.com/issues/ch000549.htm#windows7).

**Comment by mattjaf** [comment]
Awesome, thank you. added it

![image](https://user-images.githubusercontent.com/5776918/203662218-20c4c271-5727-4e7b-a925-68e83a14e803.png)

Do I need mySQL as well? Whats the latest compatible version?

**Comment by nickvanw** [comment]
@mattjaf I believe you'll just _need_ to download the MySQL Shell: https://dev.mysql.com/downloads/shell/, although the full installer should also include what you need. 

I don't know how the MySQL installer picks the right platform on Windows, but that version should work.

**Comment by orware** [comment]
Hi @mattjaf,

You may not need the MySQL pieces, unless you end up using our `pscale shell` [command](https://planetscale.com/docs/reference/shell) which is the main one that would use it.

If you do end up needing it, you should be able to grab the ZIP file from this URL:
https://dev.mysql.com/downloads/mysql/

And kind of like the installation for `pscale` I shared initially, you can extract the contents of the ZIP into something like `C:\mysql` which would result in a full path of `C:\mysql\mysql-8.0.31-winx64` for you.

Then you would want to add in the `bin` folder to your Windows PATH:

```
C:\mysql\mysql-8.0.31-winx64\bin
```

And that should give you easy access to use the `mysql.exe` command when `pscale shell` needs to use it under the hood, or would provide direct access to using other MySQL utilities that are included within the `bin` directory, without necessarily needing to run the MySQL server locally on that Windows 7 machine. 

This would likely be a bit better than using just the MySQL shell download which only seems to come with the following within its `bin` directory:
![image](https://user-images.githubusercontent.com/931650/204406587-d70ee872-7861-49ee-8b91-e9fa13d3b2f8.png)

Versus the Community Server download coming with the more common utilities:
![image](https://user-images.githubusercontent.com/931650/204406647-c2c8141e-2e3e-4748-9b07-a04d936a8689.png)
