### ISSUE TITLE
[Feature Request] project level config

### ISSUE THREAD

**Issue by robotkutya** [planetscale/cli#609]
We can currently set our default org in `~/.config/planetscale/pscale.yml` however I did not find a way to set your organization on a project (git repo) level.

It would be cool to have a local setting that takes precedence, similar to how e.g. `.nvmrc` sets the node version for the directory.

I understand I can use the `--org` flag, but that's still easy to mix up when working on multiple projects in multiple orgs.

**Comment by dbussink** [comment]
If you use `pscale` inside a Git repository, we already should do this automatically for you. See also:

https://github.com/planetscale/cli/blob/26c43c9cb483457130ed280b94f78e543eac5eab/internal/config/config.go#L100-L119

Is that not working for you?

**Comment by robotkutya** [comment]
Nope :(

Maybe I'm missing something obvious, but can you give me a super stupid example how this would look like?
So if I am in the git repo root, where should I put the config exactly with what path?

**Comment by robotkutya** [comment]
@dbussink it works, thank you!

Is this documented anywhere? I tried `pscale.yml` in my project (notice the missing dot) and that made sense to me since it matches the pattern `~/.config/planetscale/pscale.yml`

An extra sentence in the docs [here](https://planetscale.com/docs/reference/org#global-flags) would be really helpful IMHO.

**Comment by dbussink** [comment]
> An extra sentence in the docs [here](https://planetscale.com/docs/reference/org#global-flags) would be really helpful IMHO.

Would you be willing to open an issue for this on https://github.com/planetscale/docs/issues? So we can track it there as a documentation improvement? Something along the line of "document per project settings for the CLI"?

**Comment by dbussink** [comment]
> Would you be willing to open an issue for this on https://github.com/planetscale/docs/issues? So we can track it there as a documentation improvement? Something along the line of "document per project settings for the CLI"?

Thnx! Closing this one in favor of the docs issue.

**Comment by robotkutya** [comment]
@dbussink done, thanks!

https://github.com/planetscale/docs/issues/234
