### ISSUE TITLE
Allow using `pscale connect` with the serverless driver for JavaScript

### ISSUE THREAD

**Issue by jacobwgillespie** [planetscale/cli#621]
Hey! We've been using `pscale connect --execute 'pnpm dev'` in local development, to connect to our database. We've recently been using the `@planetscale/database` serverless driver and would love to be able to use that with `pscale connect` as well.

Currently the injected `DATABASE_URL` environment variable assumes the MySQL protocol - I'm not sure what would be involved in offering that same functionality but for the serverless driver, I could imagine a `--protocol http` option or similar flag to switch proxy modes.

**Comment by erikmay** [comment]
This would be a much needed feature and awesome!

**Comment by mscoutermarsh** [comment]
We're tracking this in the database.js repo here: https://github.com/planetscale/cli/issues/621

Thanks!
