### ISSUE TITLE
pscale database create permission error

### ISSUE THREAD

**Issue by danielnoh0514** [planetscale/cli#632]
I'm getting an error when I try to make a database.. 

<img width="772" alt="Screenshot 2566-03-14 at 16 45 40" src="https://user-images.githubusercontent.com/118356044/224963308-a5d165d2-cd98-4199-8356-e5cc333f5662.png">

**Comment by mscoutermarsh** [comment]
How did you authenticate with the CLI? Are you using a service token? May be possible that token does not have the `create_databases` permission?

**Comment by mscoutermarsh** [comment]
I believe this is likely due to a service token missing permission, closing for now. Please let us know if that does not solve it.
