### ISSUE TITLE
`pscale dump` omits timestamp column

### ISSUE THREAD

**Issue by ewels** [planetscale/cli#676]
Hi there,

I'm using `pscale dump` to export a database, but for some reason it is omitting the date column.

The schema looks fine:

```sql
CREATE TABLE `version_check` (
  `id` int NOT NULL AUTO_INCREMENT,
  `version` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13214907 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

But the exported file is missing the `date` column:

```sql
INSERT INTO `version_check`(`id`,`version`) VALUES
(8560305,"1.12"),
(8560306,"1.12"),
(8560307,"1.12"),
(8560308,"1.12"),
(8560309,"1.12"),
(8560310,"1.7"),
(8560311,"1.7"),
(8560312,"1.12"),
(8560313,"1.12"),
# ...
```

Viewing the table via the Planetscale web console seems fine:

![CleanShot 2023-05-16 at 16 01 23@2x](https://github.com/planetscale/cli/assets/465550/bd5261fb-2b62-400e-b698-ca42c4ff75b2)

Any ideas what's going wrong here?

```console
$ pscale --version
pscale version 0.142.0 (build date: 2023-05-04T21:50:56Z commit: 397512d)

$ uname -mpsrv
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64 arm
```

Many thanks in advance,

Phil

**Comment by orware** [comment]
@mashehu,

That should be the issue exactly! There were some recent changes in that part of the code to exclude those other cases, but it looks like it accidentally excludes the `DEFAULT_GENERATED` case too.

If you'd like to submit a PR for it that would be great, otherwise some from the team will likely be able to get this addressed before too long on our end.

**Comment by mashehu** [comment]
I will give it a try

**Comment by orware** [comment]
@mashehu, I just submitted a quick PR that I'm hoping will get this addressed. 

Once it's able to be reviewed and merged in we'll be able to see and verify that it indeed provides the needed fix for you.

**Comment by mashehu** [comment]
sorry, didn't see your PR, before adding mine. Should I close mine? I tested it with the setup from @ewels and it works fine now.

**Comment by orware** [comment]
@mashehu, No worries I would go ahead and leave it open for now as I kind of like your approach better ;-).

**Comment by ewels** [comment]
Wow, thank you both! Talk about a speedy response!

**Comment by mscoutermarsh** [comment]
This is now fixed in `v0.143.0`. Thanks all!

**Comment by ewels** [comment]
No way, I opened this issue just before stopping for the day and going in for dinner. By the time the kids are in bed you guys have found the bug, fixed it and cut a release.. Amazing! 😆 🙌🏻 

![wow](https://media.giphy.com/media/ToMjGpnXBTw7vnokxhu/giphy.gif)

Thanks for the fix! 🙇🏻

**Comment by ewels** [comment]
Fix confirmed 👍🏻 

```sql
INSERT INTO `version_check`(`id`,`version`,`date`) VALUES
(1,"1.111","2023-03-22 15:13:26"),
(9982,"0.5","2016-05-16 13:50:24"),
(9983,"0.6","2016-05-16 13:53:13"),
(9984,"0.7.dev","2016-05-16 13:54:34"),
(9985,"0.7.dev","2016-05-16 14:02:49"),
(9986,"0.5","2016-05-16 14:09:09"),
(9987,"0.7.dev","2016-05-16 14:10:11"),
(9988,"0.7.dev","2016-05-16 14:10:14"),
(9989,"0.7.dev","2016-05-16 14:10:18"),
# ...
```
