### ISSUE TITLE
[Bug] Attempting to enable safe migrations on a non-production branch fails silently

### ISSUE THREAD

**Issue by bmorrisondev** [planetscale/cli#720]
Org: bmorrison-ps
Database: recipes_db
Branch: main
Tier: Hobby
OS: Mac running Ventura 13.5
pscale version 0.147.0 

See video for details:

https://github.com/planetscale/cli/assets/4684030/9e06bcd9-d9d9-4159-92ef-12767d5ba469

**Comment by iheanyi** [comment]
Thanks for reporting this, we'll get this fixed up!
