### ISSUE TITLE
Unable to get the access token from ~/.config/planetscale/access-token

### ISSUE THREAD

**Issue by karanpopat** [planetscale/cli#729]
I want to get the access token to use for planetscale apis
After `pscale auth login`, tried `cat ~/.config/planetscale/access-token`
Unfortunately the file doesn't exist. Is there any other way to fetch the access token?

**Comment by mscoutermarsh** [comment]
Hey @karanpopat,

What operating system are you using? It's likely stored on your keychain.

You can also create a service token: https://planetscale.com/docs/concepts/service-tokens

**Comment by karanpopat** [comment]
Got the access token from the keychain.
Thanks @mscoutermarsh for the quick response
