### ISSUE TITLE
Getting `error dumping table` error while dumping database using pscale cli

### ISSUE THREAD

**Issue by harshitsaini** [planetscale/cli#730]
I'm trying to create a database dump of dev branch but getting error saying `error dumping table`

Shell Command
```shell
pscale database dump [database_name] dev --output mysql_dumps/dev/$(date +"%Y-%m-%d_%H-%M-%S") --service-token [redacted] --service-token-id [redacted] --org [redacted] --debug
```

Debug log
```shell
⠹ Dumping tables ...2023-09-10T18:39:25+05:30	error	error dumping table	{"error": "EOF"}
2023-09-10T18:39:25+05:30	info	dumping table database schema...	{"database": "redacted", "table": "redacted"}
2023-09-10T18:39:25+05:30	info	dumping table ...	{"database": "redacted", "table": "redacted", "thread_conn_id": 6}
⠴ Dumping tables ...2023-09-10T18:39:26+05:30	error	error dumping table	{"error": "EOF"}
2023-09-10T18:39:26+05:30	info	dumping all done	{"elapsed_time": "25.971499491s", "allrows": 0, "allbytes": 0, "rate_mb_seconds": 0}
Dumping is finished! (elapsed time: 45.007105241s)
```

Table schemas and metadata are downloaded successfully but table data download is failing.

**Comment by DaliborPan** [comment]
I'm having the same problem

**Comment by pjfancher** [comment]
I'm having the exact same problem. I'm using pscale database dump and the command was working fine yesterday. No big changes to the database. The database is 146MB. 

<img width="871" alt="Screen Shot 2023-09-14 at 1 09 22 PM" src="https://github.com/planetscale/cli/assets/502590/493effb7-6f2f-4e2d-8f43-119a93957fbe">

**Comment by orware** [comment]
Hello @harshitsaini, @DaliborPan, and @pjfancher,

An underlying fix on our end outside of the CLI code base has gone out that should resolve the issue with using `pscale database dump` so you should be able to use it again now!

If you experience any further issues though please let us know!

**Comment by pjfancher** [comment]
Hi @orware can confirm it is working now. Thank you so much for the help and quick responses!
