### ISSUE TITLE
Append timestamp to directory name in dump command, preventing directory name conflicts

### ISSUE THREAD

**Issue by wnelson03** [planetscale/cli#732]
In this dump command code https://github.com/planetscale/cli/blob/main/internal/cmd/database/dump.go#L159-L163

I feel it would be better if the current timestamp was appended at the end of the directory name. This would prevent directory name conflicts, which are slightly annoying to deal with.

It's common for most database engines to include a timestamp in file names during a dump. I think perhaps Planetscale CLI should behave the same.

What are your thoughts?

**Comment by mscoutermarsh** [comment]
Sounds good to me!
