### ISSUE TITLE
Error handling is causing malformed stderr

### ISSUE THREAD

**Issue by mihaigabrieldavid** [planetscale/cli#803]
Hi, everything was working fine for me until recently when a workflow started failing because the command `pscale deploy-request show ${databaseName} ${branchName} -f json --no-color` returns the following malformed `stderr`:

```
{"error": "no deploy requests found for branch update-workflows"}Updater error: skipping update, error: open /home/runner/.config/planetscale/state.yml: no such file or directory
```

I use the pscale setup step in the workflow as recommended
```
 - name: Setup Pscale
   uses: planetscale/setup-pscale-action@v1
```

I think this issue might be caused by this recent commit: https://github.com/planetscale/cli/commit/eac30493535ece157aafd7a7c35e7ca01e40223b. 

If I try to use the older version v0.175.0, even when there's no error, the stderr is still malformed and looks like this:
```
 A new release of pscale is available: 0.175.0 → v0.176.0
  https://github.com/planetscale/cli/releases/tag/v0.176.0
```
This shouldn't be included in stderr at all in my opinion.

**Comment by mscoutermarsh** [comment]
Thank you for reporting. We just released 177 with a fix for this. https://github.com/planetscale/cli/releases/tag/v0.177.0

If you see any more issues, please let us know!
