### ISSUE TITLE
pscale auth check "succeeds" even when your access token has expired

### ISSUE THREAD

**Issue by ciiqr** [planetscale/cli#836]
I have some dev scripts which first check to make sure you're logged in, and prompt you to do so if you haven't already, ie.
```bash
if ! pscale auth check >/dev/null 2>&1; then
    pscale auth login
fi

... some pscale commands
```

I ran into an issue with this where auth check returns successfully (indicating that I am authenticated), however when I go to then run some other pscale commands, it turns our that my token has actually expired:

```bash
$ pscale auth check; echo -e "\nexit: $?"
You are authenticated.
exit: 0

$ pscale org list
Error: the access token has expired. Please run 'pscale auth login'
```

Right now I have worked around this by changing the script to do the following:
```bash
if ! pscale org list >/dev/null 2>&1; then
    pscale auth login
fi
```

I would prefer, if possible, for it to not have to reach out to the api to validate; would it be reasonable to store the expiry locally when logging in so it can be checked by `pscale auth check`?
Alternatively, if that's not possible, to have `pscale auth check` check the validity of the token with the planetscale api itself?

Additional info:
```bash
$ pscale --version
pscale version 0.186.0 (build date: 2024-03-07T10:04:27Z commit: 69683e7)
```

**Comment by mscoutermarsh** [comment]
Thank you! Updated it to make an API call. Release will be published in a couple minutes.
