### ISSUE TITLE
Can't get latest version via Windows scoop

### ISSUE THREAD

**Issue by birksy89** [planetscale/cli#875]
The version which is downloads or updates to is:
```
pscale version 0.115.0 (build date: 2022-08-30T18:49:01Z commit: ce370d5)
```

I checked the repo here:
https://github.com/planetscale/scoop-bucket

And it does look like it's been updated.

I also removed the scoop bucket and re-added it, but it didn't make a difference.

I've recently got a lot of emails about using an out of date CLI, hence attempting to perform the upgrade.

Thanks 🙏

**Comment by dbussink** [comment]
> I checked the repo here: https://github.com/planetscale/scoop-bucket
> 
> And it does look like it's been updated.

Fwiw, I have no real idea how scoop works, but the repository there is updated? 

https://github.com/planetscale/scoop-bucket/blob/main/pscale.json contains references to `0.197.0` which is the latest version?

**Comment by birksy89** [comment]
Scratch this - Sorry, it does appear to update when I use Windows Powershell as an administrator.

Thanks for taking the time to respond 😄
