### ISSUE TITLE
RSS Feed or Similar functionality on changelog

### ISSUE THREAD

**Issue by tkimmm** [planetscale/cli#879]
Hi Planetscale team,

We recently had some downtime due to the deprecation of `pscale connect `commands  for proxy connectivity (outdated cli). Noticed that there was a changelog update about it on the 17th of June 2024. 

Is there a suggested way to subscribe to the changelog or be notified of upstream changes like this, couldnt see any RSS feed like functionality on the page?

Thanks

**Comment by mscoutermarsh** [comment]
Great idea, we'll add one.

**Comment by mscoutermarsh** [comment]
https://planetscale.com/changelog/rss.xml

**Comment by tkimmm** [comment]
Thanks a lot!
