### ISSUE TITLE
handle homebrew's bump to mysql@v9 on macOS

### ISSUE THREAD

**Issue by aybabtme** [planetscale/cli#916]
`pscale shell` is semi broken as of recently, because homebrew bumped mysql to v9, which doesnt contain the `.so` required for y'all's shell integration.

See https://stackoverflow.com/questions/78938322/mysql-authentication-plugin-issues-on-macos

https://gist.github.com/aybabtme/4fd51e181942405052d8e4645773a2d1

Might be good to catch that in the CLI and handle it cleanly, perhaps suggesting how to fix it at a minimum, so people don't wonder what's up.

**Comment by dbussink** [comment]
Fixed!
