### ISSUE TITLE
Can't dump/restore branches containing views (without crappy work arounds)

### ISSUE THREAD

**Issue by disco-infinex** [planetscale/cli#921]
These commands will (seemingly?) never work if the branch being dumped/restored contains a view:

```sh
pscale database dump "${DB_NAME}" test --output "${BACKUP_DIR}"
pscale branch create "${DB_NAME}" "${NEW_BRANCH}" --from "${SOURCE_BRANCH}" --wait
pscale database restore-dump "${DB_NAME}" "${NEW_BRANCH}" --dir "${BACKUP_DIR}" --overwrite-tables
```

There are several bugs contributing to this:

* The `pscale database dump` command inexplicably takes a copy of _data_ from views. Dumping a view _schema_ makes sense but the data is necessarily derived from the other data in the DB, including it just takes up space and slows the dump process. Strange this is even allowed, let alone the default.
* When restoring, the `--overwrite-tables` flag "will attempt to DROP TABLE before restoring" but has no effect on views. As such, attempting to restore a DB dump that includes views will error with `Error: failed to restore database: target: [...].-.primary: vttablet: rpc error: code = AlreadyExists desc = Table '[...]' already exists` even when `--overwrite-tables` is used. This can be avoided by deleting the views `*-schema.sql` file in the dump dir but better would be if the `--overwrite-tables` flag also apply to views or, I suppose, you could add a separate `--overwrite-views` flag.
* Deleting the views schema from the dump dir isn't enough; unless the data file is also removed the restore command will attempt to insert data into the view, resulting in an error like `error restoring {"error": "target: [...].-.primary: vttablet: rpc error: code = Unknown desc = Column 'id' is not updatable`. Again, deleting the data files dumped for the view works around the issue but surely the restore command could be smart enough to know the "table" in question is  view and skip it.

Some of this could be avoided if either the dump or restore commands had a way to exclude specific tables/views. The `--tables` argument works but is painful to use if you have 100 tables and a few views that need excluding every single time.

**Comment by orware** [comment]
@disco-infinex,

I don't typically work with datasets regularly in support that have views so I hadn't gotten a chance to try and verify what you had shared here yet but today I was working with one and definitely experienced the same behavior you described above so I'll see if I can work on some potential improvements for this over the next week or two.

**Comment by orware** [comment]
Looks like I had experienced the issue as well last year:
https://github.com/planetscale/cli/issues/701

I'm pretty sure this should be fixable however so I'll review both issues and focus on trying to get a solution put together for this 👍.

**Comment by orware** [comment]
Addressed by https://github.com/planetscale/cli/pull/932.
